name: 'linkedin'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
vars:
  linkedin:
    ad_analytics_by_creative: "{{ ref('stg_linkedin__ad_analytics_by_creative') }}"
    creative_history: "{{ ref('stg_linkedin__creative_history') }}"
    campaign_history: "{{ ref('stg_linkedin__campaign_history') }}"
    campaign_group_history: "{{ ref('stg_linkedin__campaign_group_history') }}"
    account_history: "{{ ref('stg_linkedin__account_history') }}"
  linkedin__passthrough_metrics: []
models:
  linkedin:
    +materialized: table
    +schema: linkedin
