name: 'linkedin'
version: '0.11.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  linkedin:
    ad_analytics_by_creative: "{{ ref('stg_linkedin_ads__ad_analytics_by_creative') }}"
    creative_history: "{{ ref('stg_linkedin_ads__creative_history') }}"
    campaign_history: "{{ ref('stg_linkedin_ads__campaign_history') }}"
    campaign_group_history: "{{ ref('stg_linkedin_ads__campaign_group_history') }}"
    account_history: "{{ ref('stg_linkedin_ads__account_history') }}"
    ad_analytics_by_campaign: "{{ ref('stg_linkedin_ads__ad_analytics_by_campaign') }}"
    geo: "{{ ref('stg_linkedin_ads__geo') }}"
    monthly_ad_analytics_by_member_country: "{{ ref('stg_linkedin_ads__monthly_ad_analytics_by_country') }}"
    monthly_ad_analytics_by_member_region: "{{ ref('stg_linkedin_ads__monthly_ad_analytics_by_region') }}"
  linkedin_ads__creative_passthrough_metrics: []
  linkedin_ads__campaign_passthrough_metrics: []
  linkedin_ads__monthly_ad_analytics_by_member_country_passthrough_metrics: []
  linkedin_ads__monthly_ad_analytics_by_member_region_passthrough_metrics: []
  linkedin_ads__conversion_fields: ['external_website_conversions', 'one_click_leads']

models:
  linkedin:
    +materialized: table
    +schema: linkedin_ads
