name: 'linkedin_integration_tests'
version: '1.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  linkedin:
    linkedin_ads_schema: linkedin_integration_tests_5
    linkedin_ads_account_history_identifier: "linkedin_account_history_data"
    linkedin_ads_ad_analytics_by_creative_identifier: "linkedin_ad_analytics_by_creative_data"
    linkedin_ads_campaign_group_history_identifier: "linkedin_campaign_group_history_data"
    linkedin_ads_campaign_history_identifier: "linkedin_campaign_history_data"
    linkedin_ads_creative_history_identifier: "linkedin_creative_history_data"
    linkedin_ads_ad_analytics_by_campaign_identifier: "linkedin_ad_analytics_by_campaign_data"
    linkedin_ads_geo_identifier: "linkedin_geo_data"
    linkedin_ads_monthly_ad_analytics_by_member_country_identifier: "linkedin_monthly_ad_analytics_by_member_country_data"
    linkedin_ads_monthly_ad_analytics_by_member_region_identifier: "linkedin_monthly_ad_analytics_by_member_region_data"

    linkedin_ads__campaign_passthrough_metrics: []
    linkedin_ads__creative_passthrough_metrics:
      - name: 'conversion_value_in_local_currency'
    linkedin_ads__conversion_fields: ['external_website_conversions', 'one_click_leads']

models:
  +schema: "linkedin_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: false
  linkedin_integration_tests:
    linkedin_creative_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        created_at: timestamp
        last_modified_at: timestamp
        click_uri: "{{ 'string' if target.type in ('bigquery','spark','databricks') else 'varchar' }}"
        intended_status: "{{ 'string' if target.type in ('bigquery','spark','databricks') else 'varchar' }}"
        status: "{{ 'string' if target.type in ('bigquery','spark','databricks') else 'varchar' }}"
    linkedin_ad_analytics_by_creative_data:
      +column_types:
        day: timestamp
    linkedin_account_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_group_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_monthly_ad_analytics_by_member_country_data:
      +column_types:
        cost_in_local_currency: numeric
        cost_in_usd: numeric
    linkedin_monthly_ad_analytics_by_member_region_data:
      +column_types:
        cost_in_local_currency: numeric
        cost_in_usd: numeric

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True